In [12]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from time import sleep

In [13]:
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

In [50]:
# def crawling_GoogleMap(place):
#     # 타입 변환
#     place = str(place)
#     # 크롬 드라이버 경로 지정
#     service = Service(executable_path=ChromeDriverManager().install())
#     # 웹 드라이버 실행
#     driver = webdriver.Chrome(service=service)
#     # 구글 맵 페이지 열기
#     driver.get('https://www.google.com/maps')
#     # 장소 검색
#     search_box = driver.find_element(By.XPATH,'//*[@id="searchboxinput"]')
#     search_box.send_keys(place)
#     search_button = driver.find_element(By.XPATH,'//*[@id="searchbox-searchbutton"]')
#     search_button.click()
#     sleep(5)
#     # 여러 개의 검색 결과가 나올 경우
#     try:
#         max_reviews = 0
#         # 검색 결과의 정밀도를 올리기 위한 새로고침
#         driver.refresh()
#         sleep(3)
#         #검색 창에서 결과들의 리뷰 수를 탐색
#         for i in range(50):
#             try:
#                 # 리뷰 수에 해당하는 Xpath 지정
#                 xpath = f'//*[@id="QA0Szd"]/div/div/div[1]/div[2]/div/div[1]/div/div/div[1]/div[1]/div[{i}]/div/\
#                     div[2]/div[4]/div[1]/div/div/div[2]/div[3]/div/span[2]/span/span[2]'
#                 element = driver.find_element(By.XPATH, xpath)
#                 # 괄호 안의 숫자를 추출 후 int로 변형
#                 match = re.search(r'\(([\d,]+)\)', element.text)
#                 review_count = int(match.group(1).replace(',', ''))
#                 # 가장 많은 리뷰 수를 저장하고 해당 경로의 xpath를 저장
#                 if review_count > max_reviews:
#                     max_reviews = review_count
#                     max_xpath= f'//*[@id="QA0Szd"]/div/div/div[1]/div[2]/div/div[1]/div/div/div[1]/div[1]/div[{i}]/div/a'
#             except:
#                 review_count = 0
#         # xpath를 이용해 하이퍼랩스 링크로 이동
#         result = driver.find_element(By.XPATH, max_xpath)
#         href = result.get_attribute("href")
#         driver.get(href)
#     # 한 개의 검색 결과만 나올 경우
#     except:
#         pass
#     # 리뷰 버튼을 클릭해 리뷰 페이지로 이동
#     try:
#         sleep(5)
#         reviews_tab = driver.find_element(By.XPATH,'//*[@id="QA0Szd"]/div/div/div[1]/div[2]/div/div[1]/div/div/div[3]/div/div/button[2]')
#         reviews_tab.click()
#     #검색 결과가 없거나 리뷰가 없는 경우
#     except:
#         result = {'평점' : ['평점 없음'], '리뷰' : ['리뷰 없음']}
#         df = pd.DataFrame(result)
#         df.to_excel("data/" + place + ".xlsx")
#         return
#     # 리뷰 영역의 스크롤 바를 조작하기 위해 해당 요소를 찾음
#     sleep(5)
#     review_scroll_area = driver.find_element(By.XPATH, '//*[@id="QA0Szd"]/div/div/div[1]/div[2]/div/div[1]/div/div/div[2]')
#     # 현재 스크롤 위치를 보존
#     last_height = driver.execute_script("return arguments[0].scrollHeight;", review_scroll_area)
#     scroll_count=0
#     while True:
#         # 스크롤 이동
#         driver.execute_script("arguments[0].scrollTop = arguments[0].scrollHeight;", review_scroll_area)
#         sleep(3)
#         scroll_count+=1
#         # 현재 스크롤 위치 기록
#         new_height = driver.execute_script("return arguments[0].scrollHeight;", review_scroll_area)
#         # 이전 스크롤 위치와 비교하여 더 이상 스크롤이 가능하지 않으면 반복 종료
#         if new_height == last_height:
#             break
#         # 스크롤 1회당 약 10건의 리뷰를 가져오므로 100개 이상의 스크롤이 이루어졌다면 반복 종료
#         if scroll_count >= 100:
#             break
#         # 바뀐 스크롤 위치를 현재 스크롤 위치로 다시 저장
#         last_height = new_height
#     sleep(1)
#     # 페이지를 끝까지 펼친 후 자세히 버튼을 전부 클릭
#     mores = driver.find_elements(By.XPATH, "//button[@class='w8nwRe kyuRq']")
#     for more in mores:
#         more.click()
#     # 페이지 소스 가져오기
#     page_source = driver.page_source
#     # BeautifulSoup을 사용하여 HTML 파싱
#     soup = BeautifulSoup(page_source, 'html.parser')
#     # 별점 추출
#     rates = soup.find_all('span', class_='kvMYJc')
#     rate_list = []
#     for rate in rates:
#         rate_list.append(int(rate.attrs['aria-label'][3]))
#         if len(rate_list)>=1000:
#             break
#     # 리뷰 추출
#     reviews = soup.find_all('span', class_='wiI7pd')
#     review_list= []
#     for review in reviews:
#         review_list.append(str(review))
#         if len(review_list)>=1000:
#             break
#     # 데이터프레임으로 만들기 전 어레이 개수 불일치로 인한 문제 해결
#     if len(rate_list) > len(review_list):
#         del rate_list[len(review_list):]
#     elif len(rate_list) < len(review_list):
#         rate_list.extend([None] * (len(review_list) - len(rate_list)))
#     else:
#         pass
#     result = {'평점' : rate_list, '리뷰' : review_list}
#     #데이터프레임으로 만든 후 엑셀 형식으로 저장
#     df = pd.DataFrame(result)
#     df.to_excel("data/spot/" + place.split()[0] + ".xlsx")
#     # 브라우저 종료
#     driver.quit()

In [ ]:
# crawling_GoogleMap('파주장릉')

df



# def cr(spot):
#     dfc=df[df['시도']==spot]
    
#     li=list(dfc[dfc['내/외국인']=='합계'].loc[:,['관광지','도로명']].values.tolist())
    
#     li
    
#     for place in li:
#         crawling_GoogleMap(place[1]+' '+place[0])
    


# cr('강원특별자치도')



# a = '구인사사사사'
# a.split()[0]

# df = pd.read_excel('주요관광지점 입장객(전국).xlsx')
# df

### 그래프를위한 데이터 가공

In [14]:
df = pd.read_excel('주요관광지점 입장객(전국).xlsx')

#### 전국기준_방문객이 많은 장소 순위

In [49]:
# 전국 방문객 장소별 순위 ( 합계, 내국인, 외국인)
total_df_sum=df[df['내/외국인']=='합계'].sort_values(['총계'],ascending=False)[:10]
total_df_local=df[df['내/외국인']=='내국인'].sort_values(['총계'],ascending=False)[:10]
total_df_foreigner=df[df['내/외국인']=='외국인'].sort_values(['총계'],ascending=False)[:10]
df[df['내/외국인']=='합계'].sort_values(['총계'],ascending=False)[:10]

,시도,군구,관광지,내/외국인,총계,2018년,2019년,2020년,2021년,2022년,2023년,위도,경도,범주,도로명,건물번
427,서울특별시,종로구,경복궁,합계,20861110,4447571,5346746,1019097,1085188,3382603,5579905,37.580137,126.976690,궁궐/종묘,사직로,161
429,서울특별시,중구,덕수궁,합계,12502267,1716334,2413596,1027432,1548926,2696402,3099577,37.566038,126.974548,궁궐/종묘,세종대로,99
233,경상북도,경주시,경주동궁과월지,합계,8424995,1415595,1598817,809649,1282462,1629225,1689247,35.849419,129.229057,유명사적/유적지,원화로,102
234,경상북도,경주시,불국사,합계,8087110,1311957,1603936,700377,1081816,1442991,1946033,35.790132,129.331817,유명사찰,불국로,385
236,경상북도,경주시,대릉원,합계,7501712,1191608,1443124,725769,1081410,1329114,1730687,35.838303,129.212861,왕릉/고분,계림로,9
431,서울특별시,종로구,창덕궁,합계,7392445,1664692,1785058,472875,643549,1186361,1639910,37.580839,126.990547,궁궐/종묘,율곡로,99
134,경상남도,진주시,진주성,합계,7296785,2253455,2167256,601689,525932,805775,942678,35.189944,128.080926,유명사적/유적지,남강로,626
136,경상남도,양산시,통도사,합계,7070681,2398999,2075843,402250,448356,518380,1226853,35.488286,129.064480,유명사찰,통도사로,108
432,서울특별시,중구,남산골한옥마을,합계,6589457,1431737,1479195,793341,800685,928726,1155773,37.559303,126.994434,고택/생가/민속마을,퇴계로34길,28
0,강원특별자치도,양양군,낙산사,합계,6352292,1222405,1243423,1045834,1059950,1197255,583425,38.124720,128.627394,유명사찰,낙산사로,100

#### 시도별 평균 방문객수 (합계, 외국인, 내국인)

In [132]:
# 전국 시도별 평균 방문객수 (합계, 외국인, 내국인)
# df.groupby('시도')['총계'].mean().sort_values(ascending=False)
# df.pivot_table(index='시도',columns='내/외국인',values='총계',aggfunc=['mean']).sort_values(('mean','합계'),ascending=False)
# df.pivot_table(index='시도',columns='내/외국인',values='총계',aggfunc=['mean'])[('mean','합계')].sort_values(ascending=False)
data =df.pivot_table(index='시도',columns='내/외국인',values='총계',aggfunc=['mean'])
visited_people =data.droplevel(level=0,axis=1)
visited_people

내/외국인             내국인            외국인            합계
시도
강원특별자치도  8.859495e+05    5711.428571  8.888052e+05
경기도      6.678221e+05   23280.160000  6.835520e+05
경상남도     9.340562e+05    3257.150000  9.357266e+05
경상북도     1.065948e+06   28781.850000  1.085461e+06
광주광역시    1.555378e+05     173.000000  1.555810e+05
대구광역시    3.295302e+05    1197.500000  3.297144e+05
서울특별시    5.469205e+06  841061.888889  6.310267e+06
세종특별자치시  1.231700e+04     249.000000  1.256600e+04
울산광역시    4.382887e+05    2498.000000  4.387050e+05
인천광역시    1.219899e+06    9145.000000  1.224472e+06
전라남도     6.211182e+05    2574.913043  6.220890e+05
전라북도     1.072538e+06    9696.785714  1.079325e+06
제주특별자치도  4.126942e+05   29387.000000  4.420812e+05
충청남도     7.251838e+05    5017.500000  7.268919e+05
충청북도     8.776803e+05     605.000000  8.778665e+05

#### 시도별 평균 방문객 많은 순위(내림차순)

visited_people_sorted = visited_people.sort_values('합계',ascending=False)
visited_people_sorted.index

### 시도기준_방문객이 많은 장소 순위

In [50]:
# 시도별 방문객 순위
df[(df['내/외국인']=='합계') & (df['시도']=='충청북도')].sort_values(['총계'],ascending=False)[:10]
df[(df['내/외국인']=='내국인') & (df['시도']=='충청북도')].sort_values(['총계'],ascending=False)[:10]
df[(df['내/외국인']=='외국인') & (df['시도']=='충청북도')].sort_values(['총계'],ascending=False)[:10]

,시도,군구,관광지,내/외국인,총계,2018년,2019년,2020년,2021년,2022년,2023년,위도,경도,범주,도로명,건물번
822,충청북도,단양군,구인사,외국인,2324,0,0,0,0,0,2324,37.031176,128.480073,유명사찰,구인사길,73
823,충청북도,보은군,삼년산성,외국인,52,21,31,0,0,0,0,36.488767,127.742528,유명사적/유적지,보은읍 어암리 산 1-2,NaN
824,충청북도,보은군,선병국가옥,외국인,44,44,0,0,0,0,0,36.468612,127.789865,고택/생가/민속마을,개안길,10-2
825,충청북도,보은군,동학농민혁명기념공원,외국인,0,0,0,0,0,0,0,35.632703,126.830528,유명사적/유적지,동학로,742

In [92]:
df[(df['관광지']=='경복궁') & (df['내/외국인']=='합계')]

,시도,군구,관광지,내/외국인,총계,2018년,2019년,2020년,2021년,2022년,2023년,위도,경도,범주,도로명,건물번
427,서울특별시,종로구,경복궁,합계,20861110,4447571,5346746,1019097,1085188,3382603,5579905,37.580137,126.97669,궁궐/종묘,사직로,161

### 각 장소별 년도에따른 방문객수 데이터 처리

In [128]:
# 장소,년도별 방문객수 그래프
place='경복궁'
da= df[(df['관광지']==place) & (df['내/외국인']=='합계')].loc[:,'2018년':'2023년'].values.tolist()
da.append(['2018','2019','2020','2021','2022','2023'])
da

[[4447571, 5346746, 1019097, 1085188, 3382603, 5579905],
 ['2018', '2019', '2020', '2021', '2022', '2023']]

In [131]:
# streamlit에서 line_chart형식(열이름을 써줘야되서 데이터 재구조화)
spot_df= pd.DataFrame({'headcount':da[0],'year':da[1]},index=['a','b','c','d','e','f'])
spot_df

   headcount  year
a    4447571  2018
b    5346746  2019
c    1019097  2020
d    1085188  2021
e    3382603  2022
f    5579905  2023

# 별점 관련 데이터처리

In [15]:
df = pd.read_excel('주요관광지점 입장객(전국).xlsx')

In [16]:
# 시도 이름목록 추출
datas=list(df['시도'].unique())

In [17]:
import os

In [18]:
def star(place):
    # directory변수를 보면 알수있듯이 무조건 data폴더안에 시도 폴더가 있어야됌
    sido=place
    directory = 'data/'+sido
    
    # 예시) 충청북도 안에있는 모든 파일 갖고오기
    files = os.listdir(directory)
    excel_files = []
    # 파일 목록 중에서 엑셀 파일인 것만 추려내기
    for file in files:
        if file.endswith('.xlsx') or file.endswith('.xls'):
            excel_files.append(file)
    
    
    
    
    
    # 엑셀파일당 평균 평점과 장소 이름을 모아둘 리스트
    rating=[]
    
    for excel_file in excel_files:
        # 파일 경로
        file_path = os.path.join(directory, excel_file)
        # 엑셀파일을 데이터 프레임화 시켜서 각 엑셀파일(장소)마다 평점의 평균을 뽑는다
        df = pd.read_excel(file_path)
        rating.append((df['평점'].mean(),excel_file.split('.')[0]))
    
    # 예) 충청북도의 각 장소마다의 평점을 갖고와서 내림차순으로 정렬
    rating.sort(reverse=True)
    # 예) 충청북도에서 별점 제일 높은 5개
    star_top10 = rating[0:11]
    # 예) 충청북도 전체 별점 평균
    star_sum=0
    cnt=0
    for rat in rating:
        print(rat[0])
        if rat[0] != 0:
            star_sum+=rat[0]
            cnt+=1
    
    star_mean = round(star_sum/cnt,2)
    
    return star_top10,star_mean

#### 각각의 장소 평균 평점,각 시도별 장소 평균평점 순위 ,전체 평균평점 높은순위 구하기

In [19]:
total_sido=[]
total_place=[]
for place in datas:
    star_top10,star_mean=star(place)
    x = [sc[1] for sc in star_top10]
    y = [sc[0] for sc in star_top10]
    df_sido = pd.DataFrame({'name':x,'rating':y})
    df_sido.to_csv(f'data/place/{place}_별점.csv', index=False)
    total_sido.append((star_mean,place))
    total_place.append(star_top10)

4.6820877817319095
4.666666666666667
4.5
4.5
4.4646464646464645
4.4088669950738915
4.337001375515818
4.189690721649485
4.162210338680927
4.092896174863388
3.88
4.73
4.637019230769231
4.589540412044374
4.586102719033232
4.582417582417582
4.572857142857143
4.5531197301854975
4.538461538461538
4.533333333333333
4.487804878048781
4.481481481481482
4.480392156862745
4.479166666666667
4.4774774774774775
4.427631578947368
4.403614457831325
4.397058823529412
4.387096774193548
4.329787234042553
4.329093799682035
4.239382239382239
4.223880597014926
4.213333333333333
4.2025316455696204
4.2
4.17877094972067
4.1625
4.1421319796954315
4.119047619047619
4.07093023255814
3.7209302325581395
4.788712011577424
4.675
4.655172413793103
4.608582574772432
4.597609561752988
4.547667342799189
4.529411764705882
4.523809523809524
4.511513157894737
4.463022508038585
4.451219512195122
4.4298245614035086
4.404354587869363
4.391830559757943
4.381322957198444
4.374558303886926
4.369047619047619
4.36734693877551
4.360703812316715
4.355555555555555
4.35064935064935
4.348387096774194
4.335820895522388
4.327586206896552
4.308641975308642
4.118811881188119
3.9855072463768115
3.9565217391304346
3.8181818181818183
4.6987087517934
4.6869565217391305
4.663888888888889
4.623655913978495
4.611111111111111
4.584434654919236
4.575055187637969
4.574193548387097
4.553054662379421
4.542242703533026
4.533795493934142
4.514745308310992
4.508474576271187
4.463636363636364
4.463291139240506
4.437209302325582
4.4363636363636365
4.428888888888889
4.420103092783505
4.412698412698413
4.405797101449275
4.4
4.4
4.387308533916849
4.382352941176471
4.380952380952381
4.376237623762377
4.368421052631579
4.363636363636363
4.361974405850091
4.339622641509434
4.339130434782609
4.289205702647658
4.287671232876712
4.28125
4.277915632754342
4.25
4.238961038961039
4.235
4.225589225589226
4.1940298507462686
4.190987124463519
4.175572519083969
4.171821305841925
4.138888888888889
3.9903381642512077
3.5142857142857142
4.5285714285714285
4.51948051948052
4.317073170731708
4.45703125
4.443037974683544
4.434659090909091
4.3321799307958475
4.281914893617022
4.257936507936508
4.225806451612903
4.140350877192983
3.96
3.95959595959596
3.802197802197802
4.791
4.772222222222222
4.7712765957446805
4.741621621621622
4.5813953488372094
4.533
4.389473684210526
4.337837837837838
4.239193083573487
4.617283950617284
4.590551181102362
4.487551867219917
4.386880856760375
4.385012919896641
4.36036036036036
4.154471544715447
4.015184381778742
4.660714285714286
4.6521739130434785
4.643929058663029
4.6138613861386135
4.604304635761589
4.544117647058823
4.541666666666667
4.507142857142857
4.504
4.488009592326139
4.485294117647059
4.475743348982785
4.475
4.472995090016367
4.467889908256881
4.466830466830467
4.462650602409639
4.461988304093567
4.447368421052632
4.433962264150943
4.431924882629108
4.415254237288136
4.409509202453988
4.396551724137931
4.3830188679245285
4.375
4.363302752293578
4.362637362637362
4.359060402684563
4.348643006263048
4.331932773109243
4.294117647058823
4.2727272727272725
4.257142857142857
4.236389684813753
4.219440353460972
4.190735694822888
4.185185185185185
4.17910447761194
4.17910447761194
4.172413793103448
4.137931034482759
4.133333333333334
4.094594594594595
4.0476190476190474
4.016806722689076
3.6794871794871793
3.610294117647059
3.5841584158415842
3.423076923076923
4.8076923076923075
4.616835994194485
4.516666666666667
4.491778774289985
4.438718662952646
4.431818181818182
4.4
4.3896103896103895
4.370892018779343
4.35
4.3246153846153845
4.274647887323944
4.245398773006135
4.1066666666666665
4.079646017699115
4.457671957671957
4.292808219178082
4.069510268562401
3.841726618705036
4.863636363636363
4.769230769230769
4.704081632653061
4.675675675675675
4.66728280961183
4.666666666666667
4.627659574468085
4.597014925373134
4.589743589743589
4.579439252336448
4.56420233463035
4.555926544240401
4.536585365853658
4.52
4.517857142857143
4.516546762589928
4.510028653295129
4.488888888888889
4.485849056603773
4.469945355191257
4.458893871449925
4.451492537313433
4.423076923076923
4.409733124018838
4.402877697841727
4.401129943502825
4.39622641509434
4.394871794871795
4.382352941176471
4.37603305785124
4.366141732283465
4.353253652058433
4.349514563106796
4.330739299610895
4.268817204301075
4.234567901234568
4.2272727272727275
4.188811188811189
4.170886075949367
4.1328671328671325
4.124444444444444
4.0
4.580705009276437
4.5
4.5
4.361635220125786
4.301470588235294
4.2758037225042305
4.248618784530387
4.241379310344827
4.016666666666667
3.9310344827586206
3.6923076923076925
3.641509433962264

In [20]:
# 시도별 평점 순위
total_sido.sort(reverse=True)
x = [sc[1] for sc in total_sido]
y = [sc[0] for sc in total_sido]
df_total_sido = pd.DataFrame({'name':x,'rating':y})
df_total_sido.to_csv(f'data/place/전국_시도_별점순위.csv', index=False)

In [21]:
total_sido

[(4.61, '서울특별시'),
 (4.47, '울산광역시'),
 (4.46, '광주광역시'),
 (4.45, '충청남도'),
 (4.39, '전라북도'),
 (4.39, '경상남도'),
 (4.38, '경상북도'),
 (4.37, '경기도'),
 (4.35, '강원특별자치도'),
 (4.31, '전라남도'),
 (4.24, '세종특별자치시'),
 (4.21, '대구광역시'),
 (4.19, '충청북도'),
 (4.17, '제주특별자치도'),
 (4.08, '인천광역시')]

In [22]:
# 전국 장소중 평점 순위
total_place.sort()
total_place

[[(4.154471544715447, '검단선사박물관'), (4.015184381778742, '강화전적지개소')],
 [(4.239193083573487, '영평사템플스테이')],
 [(4.45703125, '용연사'),
  (4.443037974683544, '도동서원'),
  (4.434659090909091, '대구불로고분군'),
  (4.3321799307958475, '선사유적공원'),
  (4.281914893617022, '남평문씨본리세거지'),
  (4.257936507936508, '대구옻골마을'),
  (4.225806451612903, '신숭겸장군유적지'),
  (4.140350877192983, '녹동서원'),
  (3.96, '모명재'),
  (3.95959595959596, '마비정'),
  (3.802197802197802, '노태우전대통령생가')],
 [(4.457671957671957, '제주추사관'),
  (4.292808219178082, '제주목관아지'),
  (4.069510268562401, '항몽유적지'),
  (3.841726618705036, '삼양선사유적지')],
 [(4.5285714285714285, '월봉서원빙월당'),
  (4.51948051948052, '포충사'),
  (4.317073170731708, '이장우가옥')],
 [(4.580705009276437, '배론성지'),
  (4.5, '충북 용암사'),
  (4.5, '정방사'),
  (4.361635220125786, '반야사'),
  (4.301470588235294, '구인사'),
  (4.2758037225042305, '충주탄금대'),
  (4.248618784530387, '육영수생가'),
  (4.241379310344827, '임충민공충렬사'),
  (4.016666666666667, '동학농민혁명기념공원'),
  (3.9310344827586206, '길상사'),
  (3.6923076923076925, '선병국가옥')],
 [(4.617283950617284, '두동면천전리각석'),
  (4.590551181102362, '외솔생가및기념관'),
  (4.487551867219917, '석남사'),
  (4.386880856760375, '장생포고래문화마을'),
  (4.385012919896641, '반구대암각화'),
  (4.36036036036036, '울산동헌및내아')],
 [(4.660714285714286, '초의선사유적지'),
  (4.6521739130434785, '나주목사내아'),
  (4.643929058663029, '향일암'),
  (4.6138613861386135, '불회사입구'),
  (4.604304635761589, '선암사'),
  (4.544117647058823, '고금충무사'),
  (4.541666666666667, '충의사'),
  (4.507142857142857, '장도청해진유적지'),
  (4.504, '쌍봉사'),
  (4.488009592326139, '낙안읍성민속마을'),
  (4.485294117647059, '백련사')],
 [(4.6820877817319095, '낙산사'),
  (4.666666666666667, '법흥사적멸보궁'),
  (4.5, '화암사'),
  (4.5, '청령포'),
  (4.4646464646464645, '단종장릉'),
  (4.4088669950738915, '청평사관광지'),
  (4.337001375515818, '선교장'),
  (4.189690721649485, '죽서루'),
  (4.162210338680927, '김유정문학마을'),
  (4.092896174863388, '청간정'),
  (3.88, '김삿갓유적지')],
 [(4.6987087517934, '부석사'),
  (4.6869565217391305, '불국사'),
  (4.663888888888889, '도산서원'),
  (4.623655913978495, '직지사'),
  (4.611111111111111, '박열의사기념관'),
  (4.584434654919236, '운문사'),
  (4.575055187637969, '대릉원'),
  (4.574193548387097, '경주동궁과월지'),
  (4.553054662379421, '고운사'),
  (4.542242703533026, '소수서원'),
  (4.533795493934142, '봉정사')],
 [(4.73, '화성'),
  (4.637019230769231, '미리내성지'),
  (4.589540412044374, '융건릉'),
  (4.586102719033232, '화성행궁'),
  (4.582417582417582, '영릉세종대왕'),
  (4.572857142857143, '행주산성'),
  (4.5531197301854975, '서오릉'),
  (4.538461538461538, '파주삼릉'),
  (4.533333333333333, '장릉'),
  (4.487804878048781, '안성성당'),
  (4.481481481481482, '영모재')],
 [(4.788712011577424, '노무현대통령생가'),
  (4.675, '통도사'),
  (4.655172413793103, '애국지사산돌손양원목사기념관'),
  (4.608582574772432, '진주성'),
  (4.597609561752988, '한산도제승당'),
  (4.547667342799189, '홍룡사'),
  (4.529411764705882, '밀양영남루'),
  (4.523809523809524, '충익사'),
  (4.511513157894737, '만어사'),
  (4.463022508038585, '수로왕릉'),
  (4.451219512195122, '대성동고분박물관')],
 [(4.791, '경복궁'),
  (4.772222222222222, '덕수궁'),
  (4.7712765957446805, '창덕궁'),
  (4.741621621621622, '창경궁'),
  (4.5813953488372094, '선릉정릉'),
  (4.533, '남산골한옥마을'),
  (4.389473684210526, '종묘'),
  (4.337837837837838, '태릉강릉조선왕릉전시관')],
 [(4.8076923076923075, '만인의총'),
  (4.616835994194485, '고창읍성'),
  (4.516666666666667, '실상사'),
  (4.491778774289985, '미륵사지'),
  (4.438718662952646, '광한루원'),
  (4.431818181818182, '변산반도국립공원개암사'),
  (4.4, '무장읍성'),
  (4.3896103896103895, '논개의암사논개사당'),
  (4.370892018779343, '백제왕궁박물관'),
  (4.35, '적상산사고지'),
  (4.3246153846153845, '경기전')],
 [(4.863636363636363, '수리치골성지'),
  (4.769230769230769, '현충사'),
  (4.704081632653061, '해미순교성지'),
  (4.675675675675675, '다락골줄무덤'),
  (4.66728280961183, '공세리성당'),
  (4.666666666666667, '홍산동헌'),
  (4.627659574468085, '칠백의총'),
  (4.597014925373134, '부소산성'),
  (4.589743589743589, '정림사지'),
  (4.579439252336448, '황새바위성지'),
  (4.56420233463035, '각원사')]]

In [23]:
total_li=[]
for i in total_place:
    for j in i:
        total_li.append(j)
total_li.sort(key= lambda x :x[0],reverse=True)

x = [sc[1] for sc in total_li]
y = [sc[0] for sc in total_li]
df_total_spot = pd.DataFrame({'name':x,'rating':y})
df_total_spot.to_csv(f'data/place/전국_장소_별점순위.csv', index=False)

#### 시도별 역사 명소 개수 구하기

In [3]:
df= pd.read_excel('주요관광지점입장객(전국)_final.xlsx')
df

,Unnamed: 0,시도,군구,범주,관광지,위도,경도,내/외국인,총계,2018년,2019년,2020년,2021년,2022년,2023년,도로명,건물번
0,0,서울특별시,종로구,궁궐/종묘,경복궁,37.580137,126.976690,합계,20861110,4447571,5346746,1019097,1085188,3382603,5579905,사직로,161
1,1,강원특별자치도,양양군,유명사찰,낙산사,38.124720,128.627394,내국인,6331487,1222405,1236631,1039072,1057390,1193348,582641,낙산사로,100
2,2,강원특별자치도,고성군,유명사찰,화암사,38.226831,128.469670,내국인,1841100,149090,237557,370264,223402,311802,548985,화암사길,100
3,3,서울특별시,중구,궁궐/종묘,덕수궁,37.566038,126.974548,합계,12502267,1716334,2413596,1027432,1548926,2696402,3099577,세종대로,99
4,4,경상북도,경주시,유명사적/유적지,경주동궁과월지,35.849419,129.229057,합계,8424995,1415595,1598817,809649,1282462,1629225,1689247,원화로,102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,821,경상북도,고령군,고택/생가/민속마을,산주마을,35.668185,128.170927,합계,0,0,0,0,0,0,0,산주1길,48
822,822,충청북도,단양군,유명사찰,구인사,37.031176,128.480073,외국인,2324,0,0,0,0,0,2324,구인사길,73
823,823,충청북도,보은군,유명사적/유적지,삼년산성,36.488767,127.742528,외국인,52,21,31,0,0,0,0,보은읍 어암리 산 1-2,NaN
824,824,충청북도,보은군,고택/생가/민속마을,선병국가옥,36.468612,127.789865,외국인,44,44,0,0,0,0,0,개안길,10-2
825,825,충청북도,보은군,유명사적/유적지,동학농민혁명기념공원,36.514721,127.758578,외국인,0,0,0,0,0,0,0,동학로,742

In [4]:
df['시도'].unique()

array(['서울특별시', '강원특별자치도', '경상북도', '경상남도', '충청남도', '전라북도', '경기도', '전라남도',
       '충청북도', '인천광역시', '대구광역시', '울산광역시', '제주특별자치도', '광주광역시', '세종특별자치시'],
      dtype=object)

In [5]:
list(df['범주'].unique())

['궁궐/종묘',
 '유명사찰',
 '유명사적/유적지',
 '왕릉/고분',
 '고택/생가/민속마을',
 '보물',
 '성/성터',
 '비/탑/문/각',
 '서원/향교/서당',
 '국보',
 '천연기념물']

In [6]:
li=['보물',
 '성/성터',
 '비/탑/문/각',
 '서원/향교/서당']
# df.groupby('범주').filter(lambda x : x.name in li)
df.groupby('범주').count()[['시도']]

             시도
범주
고택/생가/민속마을  221
국보            6
궁궐/종묘        15
보물            9
비/탑/문/각      23
서원/향교/서당     36
성/성터         21
왕릉/고분        35
유명사적/유적지    277
유명사찰        177
천연기념물         6

In [7]:
df.groupby('범주').count()[['시도']].T

범주,고택/생가/민속마을,국보,궁궐/종묘,보물,비/탑/문/각,서원/향교/서당,성/성터,왕릉/고분,유명사적/유적지,유명사찰,천연기념물
시도,221,6,15,9,23,36,21,35,277,177,6

In [8]:
dd=dict(df.groupby('범주').count()['관광지'])

In [9]:
dd

{'고택/생가/민속마을': 221,
 '국보': 6,
 '궁궐/종묘': 15,
 '보물': 9,
 '비/탑/문/각': 23,
 '서원/향교/서당': 36,
 '성/성터': 21,
 '왕릉/고분': 35,
 '유명사적/유적지': 277,
 '유명사찰': 177,
 '천연기념물': 6}

In [10]:
li=['국보','보물']
x=[]
val=[]
for item in li:
    if item in dd.keys():
        x.append(item)
        val.append(dd[item])
x=np.array(x)
x

array(['국보', '보물'], dtype='<U2')

In [11]:
df.groupby(['시도','범주']).count()[['군구']].unstack().fillna(0).droplevel(axis=1,level=0).reset_index()

범주,시도,고택/생가/민속마을,국보,궁궐/종묘,보물,비/탑/문/각,서원/향교/서당,성/성터,왕릉/고분,유명사적/유적지,유명사찰,천연기념물
0,강원특별자치도,13.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,9.0,10.0,0.0
1,경기도,18.0,0.0,0.0,0.0,3.0,0.0,9.0,11.0,45.0,13.0,0.0
2,경상남도,40.0,3.0,0.0,2.0,4.0,2.0,0.0,2.0,29.0,16.0,0.0
3,경상북도,65.0,0.0,0.0,2.0,7.0,11.0,5.0,2.0,23.0,40.0,3.0
4,광주광역시,2.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,2.0,0.0,0.0
5,대구광역시,8.0,0.0,0.0,0.0,0.0,7.0,0.0,2.0,8.0,3.0,0.0
6,서울특별시,3.0,0.0,15.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0
7,세종특별자치시,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
8,울산광역시,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,3.0,0.0
9,인천광역시,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0
10,전라남도,17.0,3.0,0.0,0.0,6.0,7.0,4.0,0.0,56.0,52.0,0.0
11,전라북도,5.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,37.0,4.0,3.0
12,제주특별자치도,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,9.0,0.0,0.0
13,충청남도,39.0,0.0,0.0,0.0,0.0,4.0,3.0,6.0,34.0,24.0,0.0
14,충청북도,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,9.0,0.0